const products = [
  {
    id: "p1",
    name: "Dadi's Special Traditional Mango Pickle",
    tagline: "Sun-dried green mangoes in pure cold-pressed mustard oil.",
    description: "Our signature mango pickle is made using a generations-old family recipe. Hand-cut raw green mangoes are marinated in high-quality cold-pressed mustard oil, mixed with hand-pounded spices like fennel, fenugreek, and mustard seeds, and then naturally sun-cured for 14 days to lock in the authentic, tangy, and spicy taste.",
    category: "pickles",
    price: 180,
    originalPrice: 240,
    discount: 25,
    rating: 4.8,
    reviewsCount: 312,
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=600",
    weight: "500g",
    ingredients: "Raw Mango, Cold-pressed Mustard Oil, Fennel, Fenugreek, Mustard Seeds, Turmeric, Red Chili Powder, Salt, Asafoetida (Hing).",
    benefits: "Rich in antioxidants, natural probiotic properties that aid digestion, 100% preservative-free.",
    nutritionalInfo: { "Energy": "154 kcal", "Fat": "12g", "Carbohydrates": "9g", "Protein": "1.8g" },
    inStock: true,
    isFeatured: true
  },
  {
    id: "p2",
    name: "Sweet & Tangy Sun-Dried Lemon Pickle",
    tagline: "Oil-free digestive lemon pickle cured in natural sunlight.",
    description: "A delicious, oil-free lemon pickle aged under the sun. Made with ripe, juicy yellow lemons, rock salt, carom seeds (ajwain), and a touch of organic jaggery. This pickle develops a rich, dark-brown syrup and a sweet-sour-spicy taste profile that is a perfect accompaniment to any Indian meal.",
    category: "pickles",
    price: 160,
    originalPrice: 200,
    discount: 20,
    rating: 4.7,
    reviewsCount: 185,
    image: "https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?auto=format&fit=crop&q=80&w=600",
    weight: "450g",
    ingredients: "Fresh Lemons, Rock Salt, Carom Seeds (Ajwain), Black Pepper, Organic Jaggery, Roasted Cumin, Black Salt.",
    benefits: "Zero oil, excellent for digestion, high Vitamin C content, traditional stomach-soother.",
    nutritionalInfo: { "Energy": "98 kcal", "Fat": "0.2g", "Carbohydrates": "22g", "Protein": "1.1g" },
    inStock: true,
    isFeatured: false
  },
  {
    id: "p3",
    name: "Spicy Garlic & Mustard Pickle",
    tagline: "Whole garlic cloves pickled with crushed yellow mustard seeds.",
    description: "A pungent and bold garlic pickle designed for garlic lovers. Peeled whole garlic cloves are cooked gently in mustard oil with yellow mustard seeds, red chili flakes, and vinegar. Over time, the garlic softens and becomes incredibly flavorful, offering a rich, warm punch with every bite.",
    category: "pickles",
    price: 195,
    originalPrice: 250,
    discount: 22,
    rating: 4.6,
    reviewsCount: 94,
    image: "https://images.unsplash.com/photo-1626132647523-66f5bf380027?auto=format&fit=crop&q=80&w=600",
    weight: "400g",
    ingredients: "Peeled Garlic cloves, Mustard oil, Crushed Yellow Mustard, Fenugreek, Red Chili, Turmeric, Vinegar, Salt.",
    benefits: "Boosts immunity, regulates cholesterol, garlic acts as a natural antimicrobial agent.",
    nutritionalInfo: { "Energy": "180 kcal", "Fat": "14g", "Carbohydrates": "11g", "Protein": "3.2g" },
    inStock: true,
    isFeatured: true
  },
  {
    id: "p4",
    name: "Shahi Desi Ghee Besan Ladoo",
    tagline: "Pure cow ghee and roasted chickpea flour laddoos.",
    description: "Experience the taste of royalty with our Shahi Besan Ladoo. Slowly roasted premium chickpea flour (besan) in pure A2 cow ghee until it turns golden brown and aromatic, mixed with raw sugar (bura) and garnished generously with slivered almonds, pistachios, and green cardamom.",
    category: "sweets",
    price: 299,
    originalPrice: 380,
    discount: 21,
    rating: 4.9,
    reviewsCount: 520,
    image: "https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&q=80&w=600",
    weight: "500g",
    ingredients: "Coarse Chickpea Flour, Pure Cow Ghee, Raw Sugar, Cardamom Powder, Almonds, Pistachios.",
    benefits: "Rich in energy and healthy fats, A2 cow ghee supports digestion and joint health, no artificial color.",
    nutritionalInfo: { "Energy": "480 kcal", "Fat": "26g", "Carbohydrates": "54g", "Protein": "7g" },
    inStock: true,
    isFeatured: true
  },
  {
    id: "p5",
    name: "Organic Coconut & Cardamom Ladoo",
    tagline: "Soft, juicy melt-in-mouth grated coconut sweet rounds.",
    description: "Hand-rolled freshly grated coconut laddus sweetened with light organic cane sugar and flavored with organic green cardamom. Prepared fresh in small batches daily, these ladoos are moist, soft, and have the perfect sweet balance.",
    category: "sweets",
    price: 220,
    originalPrice: 280,
    discount: 21,
    rating: 4.5,
    reviewsCount: 142,
    image: "https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?auto=format&fit=crop&q=80&w=600",
    weight: "400g",
    ingredients: "Freshly Grated Coconut, Organic Cane Sugar, Condensed Milk, Cardamom, Cashew bits.",
    benefits: "Medium Chain Triglycerides (MCTs) from coconut provide quick energy, gluten-free dessert option.",
    nutritionalInfo: { "Energy": "395 kcal", "Fat": "18g", "Carbohydrates": "52g", "Protein": "4.5g" },
    inStock: true,
    isFeatured: false
  },
  {
    id: "p6",
    name: "Homemade Premium Kaju Katli",
    tagline: "Thin, delicate cashew diamonds with silver foil (Vark).",
    description: "Our homemade Kaju Katli is prepared with nothing but premium cashews and minimal sugar syrup. We ensure zero compromise on quality by avoiding milk powder or vegetable fats, resulting in extremely smooth, creamy cashew diamonds that melt in your mouth.",
    category: "sweets",
    price: 380,
    originalPrice: 480,
    discount: 20,
    rating: 4.8,
    reviewsCount: 290,
    image: "https://images.unsplash.com/photo-1605698822071-a83ad65842a2?auto=format&fit=crop&q=80&w=600",
    weight: "400g",
    ingredients: "Premium Cashew Nuts, Sugar, Water, Rose Water, Cardamom.",
    benefits: "Rich in monounsaturated fats (heart-healthy), good source of plant-based protein and magnesium.",
    nutritionalInfo: { "Energy": "468 kcal", "Fat": "22g", "Carbohydrates": "58g", "Protein": "9.5g" },
    inStock: true,
    isFeatured: true
  },
  {
    id: "p7",
    name: "Stone-Ground Aromatic Garam Masala",
    tagline: "15-spice blend dry-roasted and slow stone-ground.",
    description: "Bring your dishes to life with our stone-ground Garam Masala. We dry-cook a blend of 15 whole spices—including black cardamom, star anise, nutmeg, and mace—at low temperatures before grinding them slowly in a traditional stone mortar (chakki) to preserve the volatile essential oils and aroma.",
    category: "spices",
    price: 130,
    originalPrice: 170,
    discount: 23,
    rating: 4.9,
    reviewsCount: 410,
    image: "https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&q=80&w=600",
    weight: "200g",
    ingredients: "Coriander, Cumin, Black Pepper, Cloves, Cardamom, Cinnamon, Nutmeg, Mace, Bay Leaves, Star Anise, Fennel.",
    benefits: "Enhances nutrient absorption, stimulates digestive enzymes, contains strong anti-inflammatory properties.",
    nutritionalInfo: { "Energy": "298 kcal", "Fat": "11g", "Carbohydrates": "42g", "Protein": "8g" },
    inStock: true,
    isFeatured: true
  },
  {
    id: "p8",
    name: "High-Curcumin Organic Turmeric Powder",
    tagline: "Pure Lakadong turmeric with over 6% curcumin content.",
    description: "Grown organically in the hills of Northeast India, this turmeric is processed in small batches by grinding dry turmeric rhizomes. Free from artificial yellow coloring, fillers, or starch, it features a deep orange hue and rich earthy taste due to its high curcumin concentration.",
    category: "spices",
    price: 110,
    originalPrice: 150,
    discount: 26,
    rating: 4.8,
    reviewsCount: 330,
    image: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&q=80&w=600",
    weight: "250g",
    ingredients: "100% Organic Lakadong Turmeric Rhizomes.",
    benefits: "Powerful anti-inflammatory and antioxidant agent, supports joint recovery and skin glow.",
    nutritionalInfo: { "Energy": "354 kcal", "Fat": "6g", "Carbohydrates": "65g", "Protein": "8g" },
    inStock: true,
    isFeatured: false
  },
  {
    id: "p9",
    name: "Roasted Cumin Powder (Jeera Masala)",
    tagline: "Freshly dry-roasted cumin seeds, ground to fine perfection.",
    description: "We pick premium cumin seeds, clean them manually, and dry-roast them on iron pans until they release a warm, nutty aroma. They are ground freshly to order. Perfect for buttermilk (chaas), curd, salads, raita, and snack seasoning.",
    category: "spices",
    price: 90,
    originalPrice: 120,
    discount: 25,
    rating: 4.7,
    reviewsCount: 165,
    image: "https://images.unsplash.com/photo-1532336414038-cf19250c5757?auto=format&fit=crop&q=80&w=600",
    weight: "150g",
    ingredients: "100% Dry-roasted Whole Cumin Seeds.",
    benefits: "Aids digestion, rich source of iron, helps control blood sugar levels.",
    nutritionalInfo: { "Energy": "375 kcal", "Fat": "22g", "Carbohydrates": "44g", "Protein": "18g" },
    inStock: true,
    isFeatured: false
  },
  {
    id: "p10",
    name: "Crispy Baked Bhakarwadi Snacks",
    tagline: "Sweet, spicy, and tangy rolled mini wheels - low oil, baked.",
    description: "A traditional Maharashtrian tea-time snack with a healthy twist. Instead of deep frying, our Bhakarwadi is baked to crispy perfection. It has a crispy gram flour outer layer rolled with a sweet, tangy, and spicy filling of poppy seeds, sesame, coconut, and spices.",
    category: "snacks",
    price: 120,
    originalPrice: 160,
    discount: 25,
    rating: 4.6,
    reviewsCount: 220,
    image: "https://images.unsplash.com/photo-1541832676-9b763b0239ab?auto=format&fit=crop&q=80&w=600",
    weight: "250g",
    ingredients: "Wheat Flour, Gram Flour, Grated Coconut, Sesame Seeds, Poppy Seeds, Sugar, Tamarind, Chili, Spices, Oil (sprayed).",
    benefits: "Baked, not fried! 70% less oil than commercial deep-fried bhakarwadi, rich in dietary fiber.",
    nutritionalInfo: { "Energy": "320 kcal", "Fat": "9g", "Carbohydrates": "52g", "Protein": "8g" },
    inStock: true,
    isFeatured: false
  },
  {
    id: "p11",
    name: "Hand-Sliced Salted Potato Wafers",
    tagline: "Sun-dried potato slices fried in fresh groundnut oil.",
    description: "Our potato wafers are made the old-fashioned way. Fresh farm potatoes are hand-sliced, washed, blanched, and then spread on sheets to sun-dry on terraces. They are fried in small batches in pure groundnut oil and sprinkled with sea salt, giving a light, crunchy, nostalgic homemade crispiness.",
    category: "snacks",
    price: 95,
    originalPrice: 120,
    discount: 20,
    rating: 4.8,
    reviewsCount: 198,
    image: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&q=80&w=600",
    weight: "200g",
    ingredients: "Potatoes, Pure Groundnut Oil, Sea Salt.",
    benefits: "No chemical bleaching, fried in fresh oil that is never recycled, preservative-free.",
    nutritionalInfo: { "Energy": "495 kcal", "Fat": "28g", "Carbohydrates": "56g", "Protein": "5g" },
    inStock: true,
    isFeatured: true
  },
  {
    id: "p12",
    name: "Diet Roasted Chivda (Poha Namkeen)",
    tagline: "Roasted flat rice mixed with curry leaves, peanuts & spices.",
    description: "A super light, crunchy tea-time snack. Thin flattened rice (poha) is roasted dry with turmeric, mustard seeds, green chilies, crispy curry leaves, and golden roasted peanuts. Sweetened slightly and salted to make it a perfect guilt-free snack.",
    category: "snacks",
    price: 110,
    originalPrice: 140,
    discount: 21,
    rating: 4.7,
    reviewsCount: 254,
    image: "https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&q=80&w=600",
    weight: "300g",
    ingredients: "Flattened Rice (Poha), Peanuts, Roasted Gram Dal, Green Chili, Curry Leaves, Turmeric, Salt, Rock Sugar.",
    benefits: "Low calorie, dry roasted with less than 1 teaspoon of oil, low glycemic index snack.",
    nutritionalInfo: { "Energy": "190 kcal", "Fat": "4g", "Carbohydrates": "34g", "Protein": "5g" },
    inStock: true,
    isFeatured: true
  },
  {
    id: "p13",
    name: "Sprouted Multigrain Energy Atta",
    tagline: "High-fiber flour made of 9 sprouted grains and seeds.",
    description: "A highly nutritious flour blend for daily chapatis. Handpicked grains (wheat, ragi, bajra, jowar, maize, barley, oats, chickpeas, and flaxseeds) are sprouted, sun-dried, roasted lightly, and ground. Sprouting multiplies the vitamin and mineral content of the grains.",
    category: "healthy",
    price: 250,
    originalPrice: 320,
    discount: 21,
    rating: 4.9,
    reviewsCount: 160,
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=600",
    weight: "2kg",
    ingredients: "Sprouted Wheat, Ragi, Jowar, Bajra, Chickpeas, Barley, Oats, Soya, Flaxseed.",
    benefits: "High protein, high fiber, sprouted grains are easy to digest and have low gluten footprint.",
    nutritionalInfo: { "Energy": "362 kcal", "Fat": "3g", "Carbohydrates": "68g", "Protein": "14g" },
    inStock: true,
    isFeatured: true
  },
  {
    id: "p14",
    name: "Raw Wild Honey (Unprocessed)",
    tagline: "Unpasteurized forest honey extracted directly from honeycombs.",
    description: "100% natural, raw wild honey harvested from the deep forests of Central India by tribal gatherers. We filter it through a simple mesh to remove wax particles, but do not heat, pasteurize, or add sugar syrup, keeping all natural enzymes, pollen, and health benefits intact.",
    category: "healthy",
    price: 340,
    originalPrice: 420,
    discount: 19,
    rating: 4.8,
    reviewsCount: 380,
    image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&q=80&w=600",
    weight: "500g",
    ingredients: "100% Pure Raw Forest Honey.",
    benefits: "Natural immunity booster, rich in phytonutrients, cures coughs, excellent healthy sweetener replacement.",
    nutritionalInfo: { "Energy": "304 kcal", "Fat": "0g", "Carbohydrates": "82g", "Protein": "0.3g" },
    inStock: true,
    isFeatured: true
  },
  {
    id: "p15",
    name: "Handmade Fruit & Nut Granola Bar",
    tagline: "Dates, oats, almonds, and pumpkin seeds toasted with honey.",
    description: "The perfect on-the-go breakfast. Whole rolled oats are mixed with almonds, cashews, pumpkin seeds, dates, and cranberries, sweetened with organic wild honey and baked to chewy perfection. Contains zero added sugar, preservatives, or artificial flavors.",
    category: "healthy",
    price: 180,
    originalPrice: 220,
    discount: 18,
    rating: 4.6,
    reviewsCount: 110,
    image: "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?auto=format&fit=crop&q=80&w=600",
    weight: "6 bars (240g)",
    ingredients: "Rolled Oats, Wild Honey, Dates, Almonds, Cashews, Pumpkin Seeds, Dried Cranberries, Cinnamon.",
    benefits: "High energy, zero refined sugar, rich in dietary fiber and healthy fats, vegan-friendly.",
    nutritionalInfo: { "Energy": "142 kcal per bar", "Fat": "5g", "Carbohydrates": "21g", "Protein": "3.5g" },
    inStock: true,
    isFeatured: false
  }
];

// Export products data globally for the browser
if (typeof window !== 'undefined') {
  window.productsData = products;
}
